### ISSUE TITLE
Maybe you could add… 

### ISSUE THREAD

**Issue by kevindevm** [briansd9/exile-diary#18]
Hi, here is an idea 💡: add a hotkey to copie the map mods and when you over a map press the hotkey a prompt would ask which zana mod. So the profit will take into account the chaos used. Thanks for this amazing app

**Comment by briansd9** [comment]
Thanks for the suggestion, but recording mapping investment (alch, zana, sextants, fragments, etc.) is somewhat outside of the scope of this app. The main reason is because it's probably impossible to do automatically, which is what I'm going for as much as possible.

If you want to do this yourself, this might help: you can add map notes by sending an @ message to yourself while in the map
