### ISSUE TITLE
Tane's Lab Back to Back

### ISSUE THREAD

**Issue by Tallion99** [briansd9/exile-diary#44]
Looks like and issue might of been introduced that doesn't allow you to run and record back to back Tane's Lab. Back on 1/2 and 1/4 I had ran several in row, each time jumping to the HO to record and going right back in. I tried it today and it records the first one fine but then seems to have an issue recording them after that. also tried going to an act and killing and then HO and ending but then the Lab is missed (the act ends ok). log attached
[log.txt](https://github.com/briansd9/exile-diary/files/4048037/log.txt)

Other than that it has been working pretty good for me! I still don't like seeing all those dead heads on it though! :)

**Comment by briansd9** [comment]
The new PoE patch causes Tane's Lab instances to be preserved when you portal out (instead of resetting every time), which means that multiple consecutive visits are now considered part of the same run.

Ran into this issue myself, still thinking about how to handle it... as a workaround, you can try doing something else between lab runs (Tane's Lab -> hideout -> (something else) -> hideout -> lab again)

**Comment by Tallion99** [comment]
Ya that might be tough to handle code wise... Thanks for all your hard work! GGG really put the screws to all the 3rd party folks this league!
