### ISSUE TITLE
Exile diary doesn't correctly identify uber elder drops

### ISSUE THREAD

**Issue by archevil** [briansd9/exile-diary#56]
Examples :

https://i.imgur.com/UP6jnuM.png voidforge as starforge

https://imgur.com/a/OtcrFLB disentegrator not identified

https://i.imgur.com/ZZpjbRd.png mark of the shaper not identified

https://i.imgur.com/43GnpgQ.png mark of the elder not identified

https://i.imgur.com/t0gjlXW.png indigon not identified

**Comment by briansd9** [comment]
Hi, thank you for reporting - Voidforge was bugged, will fix this.

For the others, that's working as I intended... the item was picked up un-ided, but you can tell the name from the art file so that's all that will be displayed. What behavior were you expecting?

Also, I am working on a proper item popup for the next release, samples (identified vs unidentified) attached below. Would this be clearer for you?

![Untitled](https://user-images.githubusercontent.com/10414098/80280178-15fadd00-8735-11ea-9ae8-a2076ea92fc2.png)

![Untitled](https://user-images.githubusercontent.com/10414098/80280602-a89c7b80-8737-11ea-9a8c-97a262e844ac.png)

**Comment by archevil** [comment]
Hi thank you for the reply, sorry wasn't checking this daily.

Maybe if it's a boss drop, the app can identify it (especially for boss drop uniques that only have a single version) so it would show up in the currency value for the specific map and would show the accurate profit from the boss map.

Yes, the new update is really nice!

Also thank you for making and updating the app :D

**Comment by briansd9** [comment]
Unique items should already be priced... the starforge example you posted is how it currently works (even though the item was misidentified).

Maybe you are filtering out low-value items? This part in the Settings screen controls that, any items under the set value are left out of the loot summary:

![Capture](https://user-images.githubusercontent.com/10414098/80452127-263ed200-8958-11ea-9a91-bd71bc571d67.JPG)

**Comment by archevil** [comment]
Ah that must be it. I set mine to 30c lol. Thank you again! :)
